import { Chat, Message, User } from './types';

// Sample users
export const users: User[] = [
  { id: '1', name: 'Periskope', avatar_url: '/avatars/periskope.png' },
  { id: '2', name: 'Roshnag Airtel', avatar_url: '/avatars/roshnag.png' },
  { id: '3', name: 'Bharat Kumar Ramesh', avatar_url: '/avatars/bharat.png' },
  { id: '4', name: 'Roshnag Jio', avatar_url: '/avatars/roshnag-jio.png' },
  { id: '5', name: 'Swapnika', avatar_url: '/avatars/swapnika.png' },
  { id: '6', name: 'Rohosen', avatar_url: '/avatars/rohosen.png' },
  { id: '7', name: 'Testing', avatar_url: '/avatars/testing.png' },
  { id: '8', name: 'Yasin', avatar_url: '/avatars/yasin.png' },
];

// Sample chat data
export const chats: Chat[] = [
  {
    id: '1',
    title: 'Test Skope Final 5',
    last_message: "Support2: This doesn't go on Tuesday...",
    last_message_time: 'Yesterday',
    unread_count: 2,
    labels: ['Demo'],
    participants: [users[0], users[1]],
  },
  {
    id: '2',
    title: 'Periskope Team Chat',
    last_message: 'Periskope: Test message',
    last_message_time: '28-Feb-25',
    unread_count: 0,
    labels: ['Demo', 'Internal'],
    participants: [users[0], users[2], users[3]],
  },
  {
    id: '3',
    title: '+91 99999 99999',
    last_message: "Hi there, I'm Swapnika, Co-Founder of ...",
    last_message_time: '25-Feb-25',
    unread_count: 0,
    labels: ['Demo', 'Signup'],
    participants: [users[4]],
  },
  {
    id: '4',
    title: 'Test Demo17',
    last_message: 'Rohosen: 123',
    last_message_time: '25-Feb-25',
    unread_count: 1,
    labels: ['Content', 'Demo'],
    participants: [users[5]],
  },
  {
    id: '5',
    title: 'Test El Centro',
    last_message: 'Roshnag: Hello, Ahmadpor!!',
    last_message_time: '04-Feb-25',
    unread_count: 0,
    labels: ['Demo'],
    participants: [users[1], users[3], users[2], users[0]],
  },
  {
    id: '6',
    title: 'Testing group',
    last_message: 'Testing 12345',
    last_message_time: '27-Jan-25',
    unread_count: 2,
    labels: ['Demo'],
    participants: [users[6]],
  },
  {
    id: '7',
    title: 'Yasin 3',
    last_message: 'First Bulk Message',
    last_message_time: '25-Nov-24',
    unread_count: 0,
    labels: ['Demo', 'Dont Send'],
    participants: [users[7]],
  },
  {
    id: '8',
    title: 'Test Skope Final 9473',
    last_message: 'Heyy',
    last_message_time: '01-Jan-25',
    unread_count: 3,
    labels: ['Demo'],
    participants: [users[0], users[1]],
  },
  {
    id: '9',
    title: 'Skope Demo',
    last_message: 'test 123',
    last_message_time: '20-Dec-24',
    unread_count: 0,
    labels: ['Demo'],
    participants: [users[1], users[2]],
  },
  {
    id: '10',
    title: 'Test Demo15',
    last_message: 'test 123',
    last_message_time: '20-Dec-24',
    unread_count: 0,
    labels: ['Demo'],
    participants: [users[5], users[0]],
  },
];

// Sample messages for Test El Centro chat
export const elCentroMessages: Message[] = [
  {
    id: '1',
    chat_id: '5',
    sender_id: '2',
    sender_name: 'Roshnag Airtel',
    content: 'CVFER',
    timestamp: '2025-01-22T11:51:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '2',
    chat_id: '5',
    sender_id: '2',
    sender_name: 'Roshnag Airtel',
    content: 'CDERT',
    timestamp: '2025-01-22T11:54:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '3',
    chat_id: '5',
    sender_id: '2',
    sender_name: 'Roshnag Airtel',
    content: 'Hello, South Euna!',
    timestamp: '2025-01-22T08:01:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '4',
    chat_id: '5',
    sender_id: '2',
    sender_name: 'Roshnag Airtel',
    content: 'Hello, Livonia!',
    timestamp: '2025-01-23T08:01:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '5',
    chat_id: '5',
    sender_id: '1',
    sender_name: 'Periskope',
    content: 'hello',
    timestamp: '2025-01-23T12:07:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '6',
    chat_id: '5',
    sender_id: '1',
    sender_name: 'Periskope',
    content: 'test el centro',
    timestamp: '2025-01-23T08:49:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '7',
    chat_id: '5',
    sender_id: '2',
    sender_name: 'Roshnag Airtel',
    content: 'CDERT',
    timestamp: '2025-01-23T09:49:00Z',
    read: true,
    type: 'text',
  },
  {
    id: '8',
    chat_id: '5',
    sender_id: '1',
    sender_name: 'Periskope',
    content: 'testing',
    timestamp: '2025-01-23T08:49:00Z',
    read: true,
    type: 'text',
  },
];

// Initial current user
export const currentUser: User = {
  id: '1',
  name: 'Periskope',
  avatar_url: '/avatars/periskope.png',
  phone: '+91 99718 44008',
};